print "---------------------ITERATION 0------------------------------------"
print "Starting Point:","628","Ending Point:","546"
print "DIJKSTRA ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","22","with bandwidth :","998"
print "DIJKSTRA HEAP ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","26","with bandwidth :","998"
print "KRUSKAL ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","30","with bandwidth :","998"
print "Timings:"
print "Dijkstra","\t","5.4813"
print "DijkstraHeap","\t","7.1186"
print "Kruskal","\t","669.5763"
print "---------------------ITERATION 1------------------------------------"
print "Starting Point:","2137","Ending Point:","3814"
print "DIJKSTRA ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","29","with bandwidth :","997"
print "DIJKSTRA HEAP ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","34","with bandwidth :","997"
print "KRUSKAL ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","74","with bandwidth :","997"
print "Timings:"
print "Dijkstra","\t","6.4199"
print "DijkstraHeap","\t","6.8978"
print "Kruskal","\t","652.0031"
print "---------------------ITERATION 2------------------------------------"
print "Starting Point:","181","Ending Point:","1598"
print "DIJKSTRA ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","39","with bandwidth :","999"
print "DIJKSTRA HEAP ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","51","with bandwidth :","999"
print "KRUSKAL ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","62","with bandwidth :","999"
print "Timings:"
print "Dijkstra","\t","4.7586"
print "DijkstraHeap","\t","5.6129"
print "Kruskal","\t","842.6439"
print "---------------------ITERATION 3------------------------------------"
print "Starting Point:","1634","Ending Point:","2493"
print "DIJKSTRA ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","45","with bandwidth :","999"
print "DIJKSTRA HEAP ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","64","with bandwidth :","999"
print "KRUSKAL ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","70","with bandwidth :","999"
print "Timings:"
print "Dijkstra","\t","5.1164"
print "DijkstraHeap","\t","7.1057"
print "Kruskal","\t","722.6934"
print "---------------------ITERATION 4------------------------------------"
print "Starting Point:","4594","Ending Point:","927"
print "DIJKSTRA ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","51","with bandwidth :","999"
print "DIJKSTRA HEAP ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","74","with bandwidth :","999"
print "KRUSKAL ALGORITHM"
print "Number of vertices traversed in maximum bandwidth path is :","89","with bandwidth :","999"
print "Timings:"
print "Dijkstra","\t","5.1584"
print "DijkstraHeap","\t","5.9235"
print "Kruskal","\t","830.6609"